FROM node:18-alpine

# Set the working directory in the Docker container
WORKDIR /app

# Copy package.json (and package-lock.json, if available) into the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
# This includes the src and public directories and any other files needed
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "start"]
